
Traceback (most recent call last):
  File "../../scripts/fun_with_classes/vf2_beauty.py", line 248, in <module>
    large_g = parse_graph(sys.argv[1])
  File "/home/max/uni/2.sem/fortbioinf/graph_alignment/scripts/fun_with_classes/parser.py", line 19, in parse_graph
    with open(doc) as d:
FileNotFoundError: [Errno 2] No such file or directory: '*_1.graph_1.graph'
Command exited with non-zero status 1
0.11


